# Generated by Django 5.2.15 on 2026-06-30 19:26

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models

SKILL_SEED_DATA = [
    {"name": "Listening", "slug": "listening", "total_lessons": 60},
    {"name": "Reading", "slug": "reading", "total_lessons": 52},
    {"name": "Writing", "slug": "writing", "total_lessons": 44},
    {"name": "Vocabulary", "slug": "vocabulary", "total_lessons": 280},
    {"name": "Speaking", "slug": "speaking", "total_lessons": 30},
]


def seed_skills_and_migrate_progress(apps, schema_editor):
    Skill = apps.get_model("app", "Skill")
    User = apps.get_model("app", "User")
    SkillProgress = apps.get_model("app", "SkillProgress")
    UserSkillProgress = apps.get_model("app", "UserSkillProgress")

    skill_by_slug = {}
    for row in SKILL_SEED_DATA:
        skill, _ = Skill.objects.update_or_create(
            slug=row["slug"],
            defaults={"name": row["name"], "total_lessons": row["total_lessons"]},
        )
        skill_by_slug[row["slug"]] = skill

    for old in SkillProgress.objects.all():
        skill = skill_by_slug.get(old.skill)
        if not skill:
            continue
        lessons = old.lessons_completed
        total = skill.total_lessons
        percent = min(100, round(lessons * 100 / total)) if total else 0
        if lessons <= 0:
            status = "not_started"
        elif percent >= 100:
            status = "completed"
        else:
            status = "in_progress"
        UserSkillProgress.objects.update_or_create(
            user_id=old.user_id,
            skill=skill,
            defaults={
                "level": old.level,
                "lessons_completed": lessons,
                "status": status,
            },
        )

    for user in User.objects.all():
        for skill in Skill.objects.all():
            UserSkillProgress.objects.get_or_create(
                user=user,
                skill=skill,
                defaults={"status": "not_started"},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_alter_skillprogress_user_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=30, unique=True)),
                ("total_lessons", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avg_accuracy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cached average accuracy (%) across scored sessions.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="study_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Cumulative practice time in hours.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="words_learned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SpeakingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tutor", models.CharField(choices=[("Miles", "Miles"), ("Maya", "Maya")], default="Miles", max_length=10)),
                ("transcript", models.JSONField(default=list, help_text="List of {role, content} chat turns.")),
                (
                    "accuracy_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Session accuracy (%) — average of per-turn scores.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="speaking_sessions", to="app.user")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSkillProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_progress", to="app.skill")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_progress", to="app.user")),
            ],
            options={
                "ordering": ["skill__name"],
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.RunPython(seed_skills_and_migrate_progress, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="SkillProgress",
        ),
    ]
