# Generated by Django 5.2.15 on 2026-06-30 21:21

import django.db.models.deletion
from django.db import migrations, models


def migrate_reading_to_skill_lessons(apps, schema_editor):
    ReadingLesson = apps.get_model("app", "ReadingLesson")
    SkillLesson = apps.get_model("app", "SkillLesson")
    Skill = apps.get_model("app", "Skill")
    UserReadingLessonCompletion = apps.get_model("app", "UserReadingLessonCompletion")
    UserSkillLessonCompletion = apps.get_model("app", "UserSkillLessonCompletion")

    reading_skill = Skill.objects.filter(slug="reading").first()
    if not reading_skill:
        return

    lesson_map = {}
    for rl in ReadingLesson.objects.all().order_by("sort_order", "id"):
        sl, _ = SkillLesson.objects.update_or_create(
            skill=reading_skill,
            slug=rl.slug,
            defaults={
                "title": rl.title,
                "passage": rl.passage,
                "question_prompt": rl.question_prompt,
                "options": rl.options,
                "correct_index": rl.correct_index,
                "level": rl.level,
                "sort_order": rl.sort_order,
                "is_published": True,
            },
        )
        lesson_map[rl.id] = sl.id

    for comp in UserReadingLessonCompletion.objects.all():
        new_lesson_id = lesson_map.get(comp.lesson_id)
        if not new_lesson_id:
            continue
        UserSkillLessonCompletion.objects.update_or_create(
            user_id=comp.user_id,
            lesson_id=new_lesson_id,
            defaults={
                "was_correct": comp.was_correct,
                "xp_earned": comp.xp_earned,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reading_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Level number (1–15) within this skill path.')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('passage', models.TextField(blank=True, help_text='Reading: passage text.')),
                ('question_prompt', models.TextField(blank=True, help_text='Reading/Listening: question text.')),
                ('options', models.JSONField(blank=True, default=list, help_text='Quiz answer options (list of strings).')),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('writing_prompt', models.TextField(blank=True, help_text='Writing: learner prompt.')),
                ('min_words', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_words', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vocab_word', models.CharField(blank=True, max_length=80)),
                ('vocab_ipa', models.CharField(blank=True, max_length=80)),
                ('vocab_meaning', models.TextField(blank=True)),
                ('vocab_example', models.TextField(blank=True)),
                ('vocab_cefr', models.CharField(blank=True, default='B2', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='practicesession',
            new_name='app_practic_user_id_a684a7_idx',
            old_name='app_practic_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='practicesession',
            new_name='app_practic_user_id_72dd41_idx',
            old_name='app_practic_user_skill_created_idx',
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='skill',
            field=models.ForeignKey(limit_choices_to={'slug__in': ('listening', 'reading', 'writing', 'vocabulary')}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.skill'),
        ),
        migrations.AddField(
            model_name='userskilllessoncompletion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app.skilllesson'),
        ),
        migrations.AddField(
            model_name='userskilllessoncompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='app.user'),
        ),
        migrations.AlterUniqueTogether(
            name='skilllesson',
            unique_together={('skill', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='userskilllessoncompletion',
            unique_together={('user', 'lesson')},
        ),
        migrations.RunPython(migrate_reading_to_skill_lessons, migrations.RunPython.noop),
    ]
