# Generated by Django 5.2.17 on 2026-08-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vocabulary_spaced_repetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('verb_tense_past_perfect', 'Past perfect vs. simple past'), ('verb_tense_present_perfect', 'Present perfect vs. simple past'), ('subject_verb_agreement', 'Subject-verb agreement'), ('articles', 'Article usage (a / an / the)'), ('prepositions', 'Preposition usage'), ('word_order', 'Word order'), ('modal_verbs', 'Modal verbs (can / could / should / would...)'), ('countable_uncountable_nouns', 'Countable vs. uncountable nouns'), ('th_sound', '"Th" sound pronunciation'), ('r_l_distinction', 'R/L sound distinction'), ('word_stress_intonation', 'Word stress and intonation'), ('false_friends_word_choice', 'False friends / word choice')], max_length=40)),
                ('example_note', models.TextField(blank=True, help_text='Latest illustrative snippet — overwritten on each reinforcement, not appended.')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Manually cleared (e.g. via admin) when a staff member judges this fixed. Reactivated automatically if the pattern is detected again.', null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='app.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to='app.user')),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_detected_at'],
                'unique_together': {('user', 'skill', 'category')},
            },
        ),
    ]
