# Generated by Django 6.0.7 on 2026-08-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tutor_error_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_freeze_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_freezes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
