# Generated by Django 6.0.7 on 2026-08-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_streak_freeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorerrorpattern',
            name='category',
            field=models.CharField(choices=[('verb_tense_past_perfect', 'Past perfect vs. simple past'), ('verb_tense_present_perfect', 'Present perfect vs. simple past'), ('subject_verb_agreement', 'Subject-verb agreement'), ('articles', 'Article usage (a / an / the)'), ('prepositions', 'Preposition usage'), ('word_order', 'Word order'), ('modal_verbs', 'Modal verbs (can / could / should / would...)'), ('countable_uncountable_nouns', 'Countable vs. uncountable nouns'), ('th_sound', '"Th" sound pronunciation'), ('r_l_distinction', 'R/L sound distinction'), ('word_stress_intonation', 'Word stress and intonation'), ('false_friends_word_choice', 'False friends / word choice'), ('spelling', 'Spelling'), ('run_on_sentences', 'Run-on sentences and comma splices'), ('punctuation', 'Punctuation usage')], max_length=40),
        ),
    ]
