# Generated by Django 6.0.7 on 2026-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_writing_error_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadinglessoncompletion',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='userreadinglessoncompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userreadinglessoncompletion',
            name='user',
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='image_credit',
            field=models.CharField(blank=True, help_text="Attribution, e.g. 'Photo by Jane Doe on Unsplash'.", max_length=200),
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='image_url',
            field=models.URLField(blank=True, help_text='Stock photo URL for photo-description items.'),
        ),
        migrations.AlterField(
            model_name='skilllesson',
            name='passage',
            field=models.TextField(blank=True, help_text='Reading: passage text. Listening: spoken-style transcript.'),
        ),
        migrations.DeleteModel(
            name='ReadingLesson',
        ),
        migrations.DeleteModel(
            name='UserReadingLessonCompletion',
        ),
    ]
