# Generated by Django 5.2.17 on 2026-09-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_skilllesson_image_drop_readinglesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=25)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='times_practiced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilllesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL for this listening item, if any.'),
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='app.user')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('passage', models.TextField(blank=True)),
                ('question_prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Shown on the results page under this question, right or wrong.')),
                ('image_url', models.URLField(blank=True)),
                ('image_credit', models.CharField(blank=True, max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.mockexam')),
            ],
            options={
                'ordering': ['exam', 'order', 'id'],
            },
        ),
    ]
